---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 'https://api.stackbit.com/project/5ead660b47dd930019bb0aa5/webhook/forestry'
sections:
  - type: document
    label: Site Configuration
    path: config.yaml
    templates:
      - config
  - type: document
    label: Home
    path: content/_index.md
    templates:
      - home
  - type: document
    label: Contact
    path: content/contact.md
    templates:
      - contact
  - type: directory
    path: content
    match: '**/*'
    exclude: '{posts/**,_index.md,contact.md}'
    label: Page
    create: all
    templates:
      - page
  - type: directory
    path: content/posts
    match: '**/*'
    label: Post
    create: all
    templates:
      - post
upload_dir: static/images
public_path: /images
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
version: '0.47'
