---
label: Site Configuration
hide_body: true
fields:
- type: text
  name: title
  label: Title
  description: Site title
  config:
    required: true
- type: text
  name: baseURL
  label: Base URL
  description: Hostname (and path) to the root
  hidden: true
- type: field_group
  name: params
  label: Params
  description: Site parameters
  config:
    required: true
  fields:
  - type: text
    name: description
    label: Site Description
    description: The default site description used in meta data.
  - type: select
    name: palette
    label: Color Palette
    description: The color palette of the theme.
    default: yellow
    config:
      source:
        type: custom
      options:
      - yellow
      - blue
      - green
      - red
  - type: field_group
    name: header
    label: Header Configuration
    fields:
    - type: text
      name: title
      label: Header Title
      description: The title displayed on the left side if no logo image added. If
        value is not set, the author name will be used.
    - type: text
      name: tagline
      label: Header Tagline
      description: The tagline displayed on the left side.
    - type: file
      name: logo_img
      label: Logo
      description: The logo image displayed on the left side.
    - type: file
      name: background_img
      label: Background Image
      description: The background image displayed on the left side.
    - type: boolean
      name: has_nav
      label: Enable Navigation Menu
      description: Display the navigation menu bar on the left side.
      default: true
    - type: field_group_list
      name: nav_links
      label: Navigation Links
      description: List of navigation links.
      fields:
      - type: include
        name: include_action
        label: Action
        template: action
      config:
        labelField: label
    - type: boolean
      name: has_social
      label: Enable Social Links
      description: Display social links on the left side.
      default: true
    - type: field_group_list
      name: social_links
      label: Social Links
      description: List of social links on the left side.
      fields:
      - type: include
        name: include_action
        label: Action
        template: action
      config:
        labelField: label
  - type: field_group
    name: footer
    label: Footer Configuration
    fields:
    - type: text
      name: content
      label: Footer Content
      description: The copyright text displayed in the footer.
    - type: field_group_list
      name: links
      label: Links
      description: List of links in the footer.
      fields:
      - type: include
        name: include_action
        label: Action
        template: action
      config:
        labelField: label
- type: list
  name: disableKinds
  label: Disable Kinds
  description: Enable disabling of all pages of the specified Kinds.
  hidden: true
  config:
    source:
      type: custom
    options:
    - page
    - home
    - section
    - taxonomy
    - taxonomyTerm
    - RSS
    - sitemap
    - robotsTXT
    - '404'
    use_select: true
- type: boolean
  name: uglyURLs
  label: Ugly URLs
  description: When enabled, creates URL of the form /filename.html instead of /filename/.
  hidden: true
